<?php
// Heading
$_['heading_title']                  = 'Оформление заказа';

// Text
$_['customer_title']                 = 'Детали клиета';
$_['text_cart']                      = 'Корзина';
$_['text_select_address']            = 'Укажите адрес';
$_['text_payment_method_title']      = 'Способ оплаты';
$_['text_delivery_method_title']      = 'Способ доставки';
$_['text_cust']                      = 'Клиент';
$_['text_log_in']                    = 'Вход';
$_['text_dilevery_address']          = 'Адрес доставки';
$_['text_checkout_option']           = 'Шаг 1: Checkout Options';
$_['text_checkout_account']          = 'Шаг 2: Account &amp; Billing Details';
$_['text_checkout_payment_address']  = 'Шаг 2: Billing Details';
$_['text_checkout_shipping_address'] = 'Шаг 3: Delivery Details';
$_['text_checkout_shipping_method']  = 'Шаг 4: Delivery Method';
$_['text_checkout_payment_method']   = 'Шаг 5: Payment Method';
$_['text_checkout_confirm']          = 'Шаг 6: Confirm Order';
$_['text_modify']                    = 'Изменить &raquo;';
$_['text_new_customer']              = 'Новый клиент';
$_['text_returning_customer']        = 'Зарегистрированый клиент';
$_['text_checkout']                  = 'Способ закза:';
$_['text_i_am_returning_customer']   = 'Я уже зарегистрирован';
$_['text_register']                  = 'Регистрация клинта';
$_['text_guest']                     = 'Гостевой заказ';
$_['text_register_account']          = 'При создании учетной записи вы сможете совершать покупки намного быстрее, быть в курсе о статусе заказа, а также отслеживать заказы, которые вы сделали ранее';
$_['text_forgotten']                 = 'Напомнить пароль';
$_['text_your_details']              = 'Ваши данные';
$_['text_your_address']              = 'Ваш адрес';
$_['text_your_password']             = 'Пароль';
$_['text_agree']                     = 'Я принимаю <a href="%s" class="agree"><b>%s</b></a>';
$_['text_address_new']               = 'Добавить новый адрес';
$_['text_address_existing']          = 'Использовать существующий адрес';
$_['text_shipping_method']           = 'Выберите способ доставки.';
$_['text_payment_method']            = 'Выберите способ оплаты.';
$_['text_comments']                  = 'Добавить комментарий к заказу';
$_['text_recurring_item']            = 'Повторяющийся платеж';
$_['text_payment_recurring']         = 'Платежный профиль';
$_['text_trial_description']         = '%s каждый %d %s(s) на %d платежей';
$_['text_payment_description']       = '%s каждый %d %s(s) на %d платежей';
$_['text_payment_cancel']            = '%s каждый %d %s(s) пока не будет отменено';
$_['text_day']                 = 'день';
$_['text_week']                = 'неделя';
$_['text_semi_month']          = 'полмесяца';
$_['text_month']               = 'месяц';
$_['text_year']                = 'год';
$_['text_login']                     = 'У меня есть аккаунт';
$_['button_order']                   = 'Заказ';
$_['text_chekout']                   = 'Оформить заказ';


// Column
$_['column_name']                    = 'Название товара';
$_['column_model']                   = 'Модель';
$_['column_quantity']                = 'Количество';
$_['column_price']                   = 'Цена';
$_['column_total']                   = 'Сумма';

// Entry
$_['entry_email_address']            = 'E-Mail';
$_['entry_email']                    = 'E-Mail';
$_['entry_password']                 = 'Пароль';
$_['entry_confirm']                  = 'Повторить пароль';
$_['entry_firstname']                = 'Имя';
$_['entry_lastname']                 = 'Фамилия';
$_['entry_telephone']                = 'Телефон';
$_['entry_fax']                      = 'Факс';
$_['entry_address']                  = 'Выберите адрес';
$_['entry_company']                  = 'Компания';
$_['entry_customer_group']           = 'Группа клиентов';
$_['entry_address_1']                = 'Адрес';
$_['entry_address_2']                = 'Адрес 2';
$_['entry_postcode']                 = 'Индекс';
$_['entry_city']                     = 'Город';
$_['entry_country']                  = 'Страна';
$_['entry_zone']                     = 'Регион';
$_['entry_newsletter']               = 'Я хочу получать рассылку от %s';
$_['entry_shipping'] 	             = 'Мой адрес совпадает с адресом доставки.';
$_['text_empty']               = 'Ваша корзина пустая!';
$_['entry_afterlogincustomer']   	= 'После авторизауии';
$_['entry_selectaddress']           = 'Выберите адрес';
// Error
$_['error_warning']                  = 'Возникла проблема при попытке обработать ваш заказ! Если проблема не устранена, пожалуйста, попробуйте выбрать другой способ оплаты или вы можете связаться с владельцем магазина <a href="%s">нажав здесь</a>.';
$_['error_login']                    = 'Внимание: Неправильные данные.';
$_['error_attempts']                 = 'Внимание: Вы заблокированы на 1 час.';
$_['error_approved']                 = 'Внимание: Ваш аккаунт ожидает модерации.';
$_['error_exists']                   = 'Внимание: E-Mail адрес уже есть а базе!';
$_['error_firstname']                = 'Имя должно содержать от 1 до 32 символов!';
$_['error_lastname']                 = 'Фамилия должна содержать от 1 до 32 символов!';
$_['error_email']                    = 'E-Mail не правильный!';
$_['error_telephone']                = 'Телефон должен содержать от 3 до 32 символов!';
$_['error_password']                 = 'Пароль должен содержать от 3 до 20 символов!';
$_['error_confirm']                  = 'Пароли не совпадают!';
$_['error_address_1']                = 'Адрес 1 должен содержать от 3 до 128 символов!';
$_['error_city']                     = 'Город должен содержать от 2 до 128 символов!';
$_['error_postcode']                 = 'Индекс должен содержать от 2 до 10 символов!';
$_['error_country']                  = 'Укажите страну!';
$_['error_zone']                     = 'Укажите регион!';
$_['error_agree']                    = 'Внимание: Вы должны принять %s!';
$_['error_address']                  = 'Внимание: Вы должны выбрать адрес!';
$_['error_shipping']                 = 'Внимание: Способ доставки обязательно!';
$_['error_no_shipping']              = 'Внимание: Нет способов доставки!';
$_['error_payment']                  = 'Внимание: Способ оплаты обязательно!';
$_['error_no_payment']               = 'Внимание: Нет способов оплаты!';
$_['error_custom_field']             = '%s обязательно!';
$_['error_stock']             			 = 'Товара *** нет в наличии в таком количестве!';
$_['error_newsletter']             	 = ' Внимание: Вы должны подписаться на рассылку!';
$_['error_address_2']             	 = 'Адрес 2 должен содержать от 3 до 128 символов!';
$_['error_company']             		 = 'Компания обязательно!';
$_['error_fax']             			   = 'Факс обязательно!';